#!/usr/bin/env python3
"""Specivo interactive setup script.

Creates .env, .env.local, the data directory structure, and a one-time
bootstrap file for the initial admin user.

Requirements: Python 3.10+ (stdlib only — no third-party packages).

Usage:
    python scripts/configure.py        # interactive
    make configure                     # same thing via Makefile
"""

from __future__ import annotations

import getpass
import json
import os
import secrets
import sys
from pathlib import Path

BANNER = r"""
 ____                  _
/ ___| _ __   ___  ___(_)_   _____
\___ \| '_ \ / _ \/ __| \ \ / / _ \
 ___) | |_) |  __/ (__| |\ V / (_) |
|____/| .__/ \___|\___|_| \_/ \___/
      |_|

  Setup wizard
"""

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def ask(prompt: str, default: str = "") -> str:
    """Prompt for input with a default value."""
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def ask_yes_no(prompt: str, default: bool = True) -> bool:
    """Prompt for a yes/no answer."""
    hint = "Y/n" if default else "y/N"
    value = input(f"{prompt} [{hint}]: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes")


def ask_password(prompt: str, min_length: int = 8) -> str:
    """Prompt for a password with confirmation."""
    while True:
        pw = getpass.getpass(f"{prompt}: ")
        if len(pw) < min_length:
            print(f"  Password must be at least {min_length} characters.")
            continue
        pw2 = getpass.getpass("  Confirm password: ")
        if pw != pw2:
            print("  Passwords do not match.")
            continue
        return pw


def create_data_dirs(data_dir: Path) -> None:
    """Create the data directory structure."""
    dirs = [
        "postgresql",
        "redis",
        "attachments",
        "themes",
        "models",
        "logs/nginx",
        "logs/app",
    ]
    for d in dirs:
        (data_dir / d).mkdir(parents=True, exist_ok=True)


def main() -> None:
    print(BANNER)

    # Check for existing configuration.
    env_path = PROJECT_ROOT / ".env"
    env_local_path = PROJECT_ROOT / ".env.local"
    if env_path.exists():
        if not ask_yes_no("Existing .env found. Overwrite?", default=False):
            print("Aborted.")
            sys.exit(0)

    # ---- Instance name ----
    print("\n--- Instance name ---")
    print("  Used as container prefix. Set different names to run")
    print("  multiple instances side by side (e.g. specivo-hr, specivo-dev).")
    instance_name = ask("Instance name", "specivo")

    # ---- Admin user ----
    print("\n--- Admin account ---")
    admin_login = ask("Admin username", "admin")
    admin_email = ask("Admin email", "admin@localhost")
    admin_password = ask_password("Admin password")

    # ---- Infrastructure mode ----
    print("\n--- Infrastructure ---")
    use_bundled_db = ask_yes_no("Use bundled PostgreSQL (Docker container)?", default=True)
    use_bundled_redis = ask_yes_no("Use bundled Redis (Docker container)?", default=True)

    database_url = ""
    pg_db = "specivo"
    pg_user = "specivo"
    pg_password = "specivo"

    if use_bundled_db:
        database_url = "postgresql+asyncpg://specivo:specivo@db:5432/specivo"
    else:
        print("\n  Provide your PostgreSQL connection URL.")
        print("  Format: postgresql+asyncpg://user:pass@host:5432/dbname")
        database_url = ask("DATABASE_URL")
        if not database_url.startswith("postgresql"):
            print("  Warning: URL should start with 'postgresql+asyncpg://'")

    if use_bundled_redis:
        redis_url = "redis://redis:6379/0"
    else:
        redis_url = ask("REDIS_URL", "redis://localhost:6379/0")

    # ---- Mailhog ----
    use_mailhog = ask_yes_no("Enable local email testing (Mailhog)?", default=False)

    # ---- Port and data directory ----
    print("\n--- Network & storage ---")
    port = ask("External port", "9933")
    data_dir_str = ask("Data directory", "./specivo-data")
    data_dir = Path(data_dir_str)

    # ---- Generate secret key ----
    secret_key = secrets.token_hex(64)

    # ---- Build COMPOSE_PROFILES ----
    profiles: list[str] = []
    if use_mailhog:
        profiles.append("mailhog")

    # ---- CORS origins ----
    cors_origins = f"http://localhost:{port}"

    # ---- SMTP settings for mailhog ----
    smtp_lines = ""
    if use_mailhog:
        smtp_lines = "\n# Mailhog (local email testing)\nSMTP_HOST=mailhog\nSMTP_PORT=1025\nSMTP_TLS=false\n"

    # ---- Create data directories ----
    create_data_dirs(PROJECT_ROOT / data_dir if not data_dir.is_absolute() else data_dir)

    # ---- Write .env ----
    env_content = f"""# Specivo configuration — generated by configure.py
# Re-run 'make configure' or 'python scripts/configure.py' to regenerate.

# Instance name (container prefix — unique per instance)
COMPOSE_PROJECT_NAME={instance_name}
"""
    if profiles:
        env_content += f"""
# Docker Compose profiles
COMPOSE_PROFILES={",".join(profiles)}
"""

    env_content += f"""
# External port
SPECIVO_PORT={port}

# Data directory (all persistent data, logs, themes)
SPECIVO_DATA_DIR={data_dir_str}

# Image version (use 'latest' or pin to a release tag)
SPECIVO_VERSION=latest

# Database
DATABASE_URL={database_url}
"""
    if use_bundled_db:
        env_content += f"""
# Bundled PostgreSQL settings
POSTGRES_DB={pg_db}
POSTGRES_USER={pg_user}
POSTGRES_PASSWORD={pg_password}
"""

    env_content += f"""
# Redis
REDIS_URL={redis_url}

# Application
DEBUG=false
REGISTRATION_MODE=open
CAPTCHA_ENABLED=false
CORS_ORIGINS={cors_origins}
{smtp_lines}"""

    env_path.write_text(env_content.strip() + "\n")
    print(f"\n  Written: {env_path}")

    # ---- Write .env.local ----
    env_local_content = f"""# Specivo secrets — DO NOT COMMIT this file.
# Generated by configure.py.

SECRET_KEY={secret_key}
"""
    env_local_path.write_text(env_local_content)
    print(f"  Written: {env_local_path}")

    # ---- Write bootstrap file ----
    bootstrap_dir = PROJECT_ROOT / data_dir if not data_dir.is_absolute() else data_dir
    bootstrap_path = bootstrap_dir / ".bootstrap.json"
    bootstrap_data = {
        "login": admin_login,
        "email": admin_email,
        "password": admin_password,
    }
    bootstrap_path.write_text(json.dumps(bootstrap_data, indent=2) + "\n")
    # Restrict permissions (non-Windows)
    if os.name != "nt":
        bootstrap_path.chmod(0o600)
    print(f"  Written: {bootstrap_path} (will be deleted after first start)")

    # ---- Summary ----
    print("\n" + "=" * 50)
    print("  Configuration complete!")
    print("=" * 50)
    print(f"""
  Instance name  : {instance_name}
  Data directory : {data_dir_str}
  Port           : {port}
  PostgreSQL     : {"bundled (Docker)" if use_bundled_db else "external"}
  Redis          : {"bundled (Docker)" if use_bundled_redis else "external"}
  Mailhog        : {f"enabled (port {8025})" if use_mailhog else "disabled"}
  Admin user     : {admin_login}
""")

    # ---- Next steps ----
    if os.name == "nt":
        print("  Next steps (Windows):")
        print("    docker compose up -d")
        print(f"    Open http://localhost:{port}/")
    else:
        print("  Next steps:")
        print("    make up")
        print(f"    Open http://localhost:{port}/")

    print()


if __name__ == "__main__":
    main()
